### ISSUE TITLE
[Feature Request] Underground Biomes Constructs compatibility

### ISSUE THREAD

**Issue by ghost** [thehobojoe/EnderOre#1]
Minecraft version: 1.10.2

The mod Underground Biomes Constructs replaces the vanilla stone with different stone types like rhyolite, soapstone, marble etc. As these different stone types contain the ores, the textures of the ores have to be changed when UBC is installed. UBC provides an API for this task.

Short: Please make Ender ore fit the UBC stone textures.

**Comment by thehobojoe** [comment]
Out of scope. The built in generator is intentionally simple, set up for just standard generation. If more robust gen is needed, one of the existing generator mods should be used.
